FROM jenkins/ssh-agent:latest-alpine-jdk11

ENV JAVA_HOME "/opt/java/openjdk"
ENV JAVA_PATH "/opt/java/openjdk/bin"

USER root

RUN apk update && \
    apk add --no-cache build-base \
                       bash \
                       zip \
                       curl \
                       wget \
                       docker-compose \
                       unzip \
                       docker \
                       git \
                       openrc \
    && \
    rm -rf /var/cache/apk/*

RUN addgroup jenkins docker


RUN rc-update add docker boot


RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/kubectl

