FROM jenkins/ssh-agent:jdk11

ENV DEBIAN_FRONTEND "noninteractive"
ENV JAVA_HOME "/usr/local/openjdk-11"
ENV JAVA_PATH "/usr/local/openjdk-11/bin"

RUN apt-get update && apt-get install -y lsb-release git curl
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
RUN useradd docker
RUN usermod -aG docker jenkins
# RUN usermod -aG ssh_keys jenkins
# USER jenkins

